version: "3"
services:
  url-shorner:
    container_name: url-shortener
    volumes:
        - ./database:/app/database
    build:
      dockerfile: Dockerfile
    ports:
      - 80:3000
    restart: always
    environment:
      urlShortenerPath: "/url"
      urlShortenerPassword: "some-password"
